### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by gedw99** [JohnKinyanjui/surrealgo_migrate#1]
I just started using this and it's really useful. thank you is all I wanted to say.

I guess you know about https://github.com/Odonno/surrealdb-migrations ?

**Comment by JohnKinyanjui** [comment]
No problem happy I could help and yes I know about the rust library it was one of the motivations why I created this cli app.

**Comment by JohnKinyanjui** [comment]
dont forget to leave a star to support the project

**Comment by gedw99** [comment]
Will do mate.

if you have anything I can help with let me know.

I am building a basic gui and cli for surreal which is using this repo

**Comment by JohnKinyanjui** [comment]
Best of your luck in your project and you can use the repo as much you want also I will let you know if there any help needed.
